id: P008185
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:06:42.654862
source_metadata:
  id: bdr:W1KG1097
  title: ཀརྨ་རཏྣའི་སྨན་ཡིག་གཅེས་བཏུས།
  author: ''
  volumes:
    765c8dff5e2641b9894c49682127672f:
      image_group_id: I1KG1117
      title: ''
      volume_number: 1
      total_pages: 436
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
