id: I1ECF8F9F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:53:10+00:00'
last_modified: '2022-06-09T05:05:30.729900+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1097
  title: ཀརྨ་རཏྣའི་སྨན་ཡིག་གཅེས་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7582':
      image_group_id: I1KG1117
      title: ''
      total_pages: 436
      order: 1
      base_file: 7582.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
